// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type DesignSystem struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PaletteData string         `json:"palette_data"`
	ConfigData  string         `json:"config_data"`
	IsPublic    sql.NullBool   `json:"is_public"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Order struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	StripePaymentIntentID sql.NullString `json:"stripe_payment_intent_id"`
	Status                string         `json:"status"`
	TotalAmount           int64          `json:"total_amount"`
	ShippingAddress       string         `json:"shipping_address"`
	ShipstationOrderID    sql.NullString `json:"shipstation_order_id"`
	TrackingNumber        sql.NullString `json:"tracking_number"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID             int64        `json:"id"`
	OrderID        int64        `json:"order_id"`
	DesignSystemID int64        `json:"design_system_id"`
	ProductType    string       `json:"product_type"`
	Quantity       int64        `json:"quantity"`
	UnitPrice      int64        `json:"unit_price"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type User struct {
	ID               int64          `json:"id"`
	ClerkID          string         `json:"clerk_id"`
	Email            string         `json:"email"`
	Name             sql.NullString `json:"name"`
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}
