// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateDesignSystem(ctx context.Context, arg CreateDesignSystemParams) (DesignSystem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDesignSystem(ctx context.Context, arg DeleteDesignSystemParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetDesignSystem(ctx context.Context, id int64) (DesignSystem, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrderByStripePaymentIntent(ctx context.Context, stripePaymentIntentID sql.NullString) (Order, error)
	GetUserByClerkID(ctx context.Context, clerkID string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error)
	ListPublicDesignSystems(ctx context.Context, arg ListPublicDesignSystemsParams) ([]DesignSystem, error)
	ListUserDesignSystems(ctx context.Context, arg ListUserDesignSystemsParams) ([]DesignSystem, error)
	ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateDesignSystem(ctx context.Context, arg UpdateDesignSystemParams) error
	UpdateOrderShipping(ctx context.Context, arg UpdateOrderShippingParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
