[phases.setup]
nixPkgs = ["go", "nodejs"]

[phases.install]
cmds = [
  "go mod download",
  "npm install",
  "go install github.com/a-h/templ/cmd/templ@latest",
  "go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest"
]

[phases.build]
cmds = [
  "sqlc generate",
  "templ generate",
  "npm run build:css",
  "mkdir -p bin",
  "go build -o bin/server cmd/server/main.go"
]

[start]
cmd = "./bin/server"
